# Enterprise HR Analytics & Employee Intelligence

## Phase 3.1 — Data Loading

This notebook connects Python to the MySQL database
`enterprise_hr_analytics` and loads the HR datasets
for further analysis.

### Data Sources
- employees
- performance_ratings

### Tools
- Python
- Jupyter Notebook
- Pandas
- NumPy
- MySQL

In [2]:
# Import required libraries
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.3
NumPy version: 2.5.1

In [3]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in C:\Users\Shiva\AppData\Local\Programs\Python\Python314\Lib\site-packages (9.7.0)

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
# Import MySQL Connector
import mysql.connector

print("MySQL connector imported successfully!")

MySQL connector imported successfully!

In [5]:
# Connect Python to MySQL
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="1612",
    database="enterprise_hr_analytics",
    port=3306
)

if connection.is_connected():
    print("MySQL connection successful!")
    print("Connected database: enterprise_hr_analytics")

MySQL connection successful!
Connected database: enterprise_hr_analytics

In [8]:
# Load employees table from MySQL

query_employees = """
select *
from employees;
"""

employees_df = pd.read_sql(query_employees, connection)


print("Employees data loaded successfully!")
print("Rows:", employees_df.shape[0])
print("Columns:", employees_df.shape[1])

C:\Users\Shiva\AppData\Local\Temp\ipykernel_17144\393261809.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  employees_df = pd.read_sql(query_employees, connection)

Employees data loaded successfully!
Rows: 1470
Columns: 23

In [9]:
# Preview the first 10 employee records
employees_df.head(10)

,EmployeeID,FirstName,LastName,Gender,Age,BusinessTravel,Department,DistanceFromHome_KM,State,Ethnicity,...,MaritalStatus,Salary,StockOptionLevel,OverTime,HireDate,Attrition,YearsAtCompany,YearsInMostRecentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,001A-8F88,Christy,Jumel,Male,22,Some Travel,Technology,40,CA,White,...,Married,27763.0,0,No,2021-09-05,No,1,0,1,0
1,005C-E0FB,Fin,O'Halleghane,Non-Binary,24,Frequent Traveller,Sales,17,CA,White,...,Married,56155.0,1,No,2017-08-26,No,5,2,2,0
2,00A3-2445,Wyatt,Ziehm,Male,30,Some Travel,Technology,6,CA,Black or African American,...,Married,126238.0,0,No,2012-03-08,No,10,3,6,6
3,00B0-F199,Trueman,Jirasek,Male,23,Some Travel,Sales,35,CA,White,...,Married,97824.0,1,Yes,2020-03-16,Yes,1,0,1,0
4,00D4-DD53,Joyce,Goor,Female,30,Frequent Traveller,Technology,44,CA,Black or African American,...,Single,68508.0,0,Yes,2012-01-28,Yes,5,4,4,4
5,00E4-3D60,Sherilyn,Girke,Female,30,Frequent Traveller,Technology,37,CA,White,...,Single,109778.0,0,No,2022-06-23,Yes,0,0,0,0
6,0145-DBFC,Keelia,Studde,Female,34,No Travel,Technology,8,CA,Asian or Asian American,...,Single,104268.0,0,No,2014-02-10,No,8,7,7,7
7,0172-B5D2,Ketti,Keighley,Female,27,Some Travel,Technology,28,CA,White,...,Married,93291.0,0,No,2020-09-11,No,2,1,2,1
8,017D-0B97,Maison,Werndley,Male,20,Some Travel,Sales,39,CA,White,...,Married,22558.0,1,Yes,2020-03-30,No,2,0,1,1
9,018B-DF1E,Otha,Sopper,Female,19,Some Travel,Sales,1,CA,White,...,Single,24499.0,0,Yes,2022-10-17,No,0,0,0,0

In [11]:
# Check the dimensions of the employee dataset
employees_df.shape

(1470, 23)

In [12]:
# Load performance ratings table from MySQL

query_performance = """
select *
from performance_ratings;
"""

performance_df = pd.read_sql(query_performance, connection)

print("Performance ratings data loaded successfully!")
print("Rows:", performance_df.shape[0])
print("Columns:", performance_df.shape[1])

C:\Users\Shiva\AppData\Local\Temp\ipykernel_17144\30144829.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  performance_df = pd.read_sql(query_performance, connection)

Performance ratings data loaded successfully!
Rows: 6709
Columns: 11

In [13]:
# Check performance dataset dimension

print("Shape:", performance_df.shape)
print("\nColumns:")
print(performance_df.columns.to_list())

Shape: (6709, 11)

Columns:
['PerformanceID', 'EmployeeID', 'ReviewDate', 'EnvironmentSatisfaction', 'JobSatisfaction', 'RelationshipSatisfaction', 'TrainingOpportunitiesWithinYear', 'TrainingOpportunitiesTaken', 'WorkLifeBalance', 'SelfRating', 'ManagerRating']

In [14]:
# Preview first 10 performance records
performance_df.head(10)

,PerformanceID,EmployeeID,ReviewDate,EnvironmentSatisfaction,JobSatisfaction,RelationshipSatisfaction,TrainingOpportunitiesWithinYear,TrainingOpportunitiesTaken,WorkLifeBalance,SelfRating,ManagerRating
0,PR01,79F7-78EC,2013-01-02,5,4,5,1,0,4,4,4
1,PR02,B61E-0F26,2013-01-03,5,4,4,1,3,4,4,3
2,PR03,F5E3-48BB,2013-01-03,3,4,5,3,2,3,5,4
3,PR04,0678-748A,2013-01-04,5,3,2,2,0,2,3,2
4,PR05,541F-3E19,2013-01-04,5,2,3,1,0,4,4,3
5,PR06,F93E-BDEF,2013-01-04,3,3,2,2,0,4,4,4
6,PR07,9E7A-1F70,2013-01-08,3,4,5,2,1,5,4,3
7,PR08,05ED-92F1,2013-01-10,4,5,4,1,1,3,3,2
8,PR09,F72D-261D,2013-01-10,4,5,2,1,1,4,5,4
9,PR10,774E-685D,2013-01-11,5,4,3,2,3,4,5,4

In [15]:
# Confirm both dataste are available

print("Employees Datafram:")
print(employees_df.shape)

print("\nPerformance Dataframe:")
print(performance_df.shape)

Employees Datafram:
(1470, 23)

Performance Dataframe:
(6709, 11)

In [16]:
# Check missing values in employees dataset

employee_missing = employees_df.isnull().sum()
print(employee_missing)

EmployeeID                 0
FirstName                  0
LastName                   0
Gender                     0
Age                        0
BusinessTravel             0
Department                 0
DistanceFromHome_KM        0
State                      0
Ethnicity                  0
Education                  0
EducationField             0
JobRole                    0
MaritalStatus              0
Salary                     0
StockOptionLevel           0
OverTime                   0
HireDate                   0
Attrition                  0
YearsAtCompany             0
YearsInMostRecentRole      0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

In [17]:
# check missing values inperformance dataset

performance_missing = performance_df.isnull().sum()
print(performance_missing)

PerformanceID                      0
EmployeeID                         0
ReviewDate                         0
EnvironmentSatisfaction            0
JobSatisfaction                    0
RelationshipSatisfaction           0
TrainingOpportunitiesWithinYear    0
TrainingOpportunitiesTaken         0
WorkLifeBalance                    0
SelfRating                         0
ManagerRating                      0
dtype: int64

In [18]:
# Check duplicate records

print("Duplicate employee records:",employees_df.duplicated().sum())

print("Duplicate employee records:", performance_df.duplicated().sum())

Duplicate employee records: 0
Duplicate employee records: 0

In [19]:
# check data type of employee columns
employees_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   EmployeeID               1470 non-null   str
 1   FirstName                1470 non-null   str
 2   LastName                 1470 non-null   str
 3   Gender                   1470 non-null   str
 4   Age                      1470 non-null   int64
 5   BusinessTravel           1470 non-null   str
 6   Department               1470 non-null   str
 7   DistanceFromHome_KM      1470 non-null   int64
 8   State                    1470 non-null   str
 9   Ethnicity                1470 non-null   str
 10  Education                1470 non-null   int64
 11  EducationField           1470 non-null   str
 12  JobRole                  1470 non-null   str
 13  MaritalStatus            1470 non-null   str
 14  Salary                   1470 non-null   float64
 15  StockOptionLevel         1470 non-null   int64
 16  OverTime                 1470 non-null   str
 17  HireDate                 1470 non-null   object
 18  Attrition                1470 non-null   str
 19  YearsAtCompany           1470 non-null   int64
 20  YearsInMostRecentRole    1470 non-null   int64
 21  YearsSinceLastPromotion  1470 non-null   int64
 22  YearsWithCurrManager     1470 non-null   int64
dtypes: float64(1), int64(8), object(1), str(13)
memory usage: 264.3+ KB

In [20]:
# Check data types of performance columns
performance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6709 entries, 0 to 6708
Data columns (total 11 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   PerformanceID                    6709 non-null   str
 1   EmployeeID                       6709 non-null   str
 2   ReviewDate                       6709 non-null   object
 3   EnvironmentSatisfaction          6709 non-null   int64
 4   JobSatisfaction                  6709 non-null   int64
 5   RelationshipSatisfaction         6709 non-null   int64
 6   TrainingOpportunitiesWithinYear  6709 non-null   int64
 7   TrainingOpportunitiesTaken       6709 non-null   int64
 8   WorkLifeBalance                  6709 non-null   int64
 9   SelfRating                       6709 non-null   int64
 10  ManagerRating                    6709 non-null   int64
dtypes: int64(8), object(1), str(2)
memory usage: 576.7+ KB

In [21]:
# Check EmployeeID uniqueness

print("Total employee records:", len(employees_df))
print("Unique EmployeeIDS:", employees_df["EmployeeID"].nunique())
print("Duplicate EmployeeIDs:", employees_df["EmployeeID"].duplicated().sum())

Total employee records: 1470
Unique EmployeeIDS: 1470
Duplicate EmployeeIDs: 0

In [22]:
#  Check EmployeeIDs in performance data

employee_ids = set(employees_df["EmployeeID"])
performance_employee_ids = set(performance_df["EmployeeID"])

missing_employee_ids = performance_employee_ids - employee_ids

print("Performance EmployeeIDs not found in employees table:", len(missing_employee_ids))

Performance EmployeeIDs not found in employees table: 0