# Enterprise HR Analytics & Employee Intelligence

## Phase 3.2 — Data Cleaning

This notebook performs data cleaning and preparation
for the HR Analytics project.

### Data Sources
- employees
- performance_ratings

### Cleaning Tasks
- Standardize column names
- Identify and handle missing values
- Identify and remove duplicate records
- Correct data types
- Convert date columns
- Validate categorical values
- Validate numerical values
- Prepare clean datasets for analysis

### Tools
- Python
- Jupyter Notebook
- Pandas
- NumPy
- MySQL

In [1]:
# Import required libraries
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
# Import MySQL connector
import mysql.connector
print("MySQL connector imported successfully!")

MySQL connector imported successfully!

In [3]:
# Connect to the HR Analytics MySQL database

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="1612",
    database="enterprise_hr_analytics",
    port=3306
)

if connection.is_connected():
    print("MySQL connection successful!")
    print("Connected database: enterprise_hr_analytics")

MySQL connection successful!
Connected database: enterprise_hr_analytics

In [4]:
# Load employees table

employees_df = pd.read_sql(
    "select * from employees;",
    connection
)

print("Employees loaded:", employees_df.shape)

Employees loaded: (1470, 23)

C:\Users\Shiva\AppData\Local\Temp\ipykernel_12856\2917743542.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  employees_df = pd.read_sql(

In [5]:
# Load employees table

performance_df = pd.read_sql(
    "select * from performance_ratings;",
    connection
)

print("Performance ratings loaded:", performance_df.shape)

C:\Users\Shiva\AppData\Local\Temp\ipykernel_12856\1401052550.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  performance_df = pd.read_sql(

Performance ratings loaded: (6709, 11)

In [6]:
# Record original dataset information

print("ORIGINAL DATASET SUMMARY")

print("\nEmployees:")
print("Rows:", employees_df.shape[0])
print("Columns:", employees_df.shape[1])
print("Duplicates:", employees_df.duplicated().sum())

print("\nPerformance Ratings:")
print("Rows:", performance_df.shape[0])
print("Columns:", performance_df.shape[1])
print("Duplicates:", performance_df.duplicated().sum())

ORIGINAL DATASET SUMMARY

Employees:
Rows: 1470
Columns: 23
Duplicates: 0

Performance Ratings:
Rows: 6709
Columns: 11
Duplicates: 0

In [7]:
# Standardize column names

employees_df.columns =(
    employees_df.columns.str.strip().str.replace(" ","_")
)
performance_df.columns =(
    performance_df.columns.str.strip().str.replace(" ","_")
)

print("Empoyees columns:", employees_df.columns.to_list())
print("\nPerformance Ratings columns:", performance_df.columns.to_list())

Empoyees columns: ['EmployeeID', 'FirstName', 'LastName', 'Gender', 'Age', 'BusinessTravel', 'Department', 'DistanceFromHome_KM', 'State', 'Ethnicity', 'Education', 'EducationField', 'JobRole', 'MaritalStatus', 'Salary', 'StockOptionLevel', 'OverTime', 'HireDate', 'Attrition', 'YearsAtCompany', 'YearsInMostRecentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

Performance Ratings columns: ['PerformanceID', 'EmployeeID', 'ReviewDate', 'EnvironmentSatisfaction', 'JobSatisfaction', 'RelationshipSatisfaction', 'TrainingOpportunitiesWithinYear', 'TrainingOpportunitiesTaken', 'WorkLifeBalance', 'SelfRating', 'ManagerRating']

In [8]:
# Check missing values in employees table
print("EMPLOYEES MISSING VALUES")
employees_missing = employees_df.isnull().sum()
print(employees_missing[employees_missing > 0])

EMPLOYEES MISSING VALUES
Series([], dtype: int64)

In [9]:
# Check missing values in performance ratings table
print("PERFORMANCE RATINGS MISSING VALUES ")
performance_missing = performance_df.isnull().sum()
print(performance_missing[performance_missing > 0])

PERFORMANCE RATINGS MISSING VALUES
Series([], dtype: int64)

In [10]:
# Analyze missing values

print("EMPLOYEES TABLE")

employees_missing = pd.DataFrame({
    "Missing_Count": employees_df.isnull().sum(),
    "Missing_Percentage": (
        employees_df.isnull().sum() / len(employees_df) * 100
    ).round(2)
})

print(employees_missing[employees_missing["Missing_Count"] > 0])


print("\nPERFORMANCE RATINGS TABLE")

performance_missing = pd.DataFrame({
    "Missing_Count": performance_df.isnull().sum(),
    "Missing_Percentage": (
        performance_df.isnull().sum() / len(performance_df) * 100
    ).round(2)
})

print(performance_missing[performance_missing["Missing_Count"] > 0])

EMPLOYEES TABLE
Empty DataFrame
Columns: [Missing_Count, Missing_Percentage]
Index: []

PERFORMANCE RATINGS TABLE
Empty DataFrame
Columns: [Missing_Count, Missing_Percentage]
Index: []

In [11]:
# Check duplicate records

print("DUPLICATE CHECK")

print("Employees duplicate rows:",
      employees_df.duplicated().sum())

print("Performance ratings duplicate rows:",
      performance_df.duplicated().sum())

DUPLICATE CHECK
Employees duplicate rows: 0
Performance ratings duplicate rows: 0

In [12]:
# Check current data types

print(" EMPLOYEES DATA TYPES")
print(employees_df.dtypes)

print("\nPERFORMANCE RATINGS DATA TYPES")
print(performance_df.dtypes)

 EMPLOYEES DATA TYPES
EmployeeID                     str
FirstName                      str
LastName                       str
Gender                         str
Age                          int64
BusinessTravel                 str
Department                     str
DistanceFromHome_KM          int64
State                          str
Ethnicity                      str
Education                    int64
EducationField                 str
JobRole                        str
MaritalStatus                  str
Salary                     float64
StockOptionLevel             int64
OverTime                       str
HireDate                    object
Attrition                      str
YearsAtCompany               int64
YearsInMostRecentRole        int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

PERFORMANCE RATINGS DATA TYPES
PerformanceID                         str
EmployeeID                            str
ReviewDate                         object
EnvironmentSatisfaction             int64
JobSatisfaction                     int64
RelationshipSatisfaction            int64
TrainingOpportunitiesWithinYear     int64
TrainingOpportunitiesTaken          int64
WorkLifeBalance                     int64
SelfRating                          int64
ManagerRating                       int64
dtype: object

In [13]:
# Convert HireDate to datetime

employees_df["HireDate"] = pd.to_datetime(
    employees_df["HireDate"],
    errors="coerce"
)

print("HireDate data type:",
      employees_df["HireDate"].dtype)

HireDate data type: datetime64[s]

In [14]:
# Convert ReviewDate to datetime

performance_df["ReviewDate"] = pd.to_datetime(
    performance_df["ReviewDate"],
    format="%m/%d/%Y",
    errors="coerce"
)

print("ReviewDate data type:",
      performance_df["ReviewDate"].dtype)

ReviewDate data type: datetime64[s]

In [15]:
# Check invalid dates after conversion

print("Invalid HireDate values:",
      employees_df["HireDate"].isna().sum())

print("Invalid ReviewDate values:",
      performance_df["ReviewDate"].isna().sum())

Invalid HireDate values: 0
Invalid ReviewDate values: 0

In [16]:
# Preview cleaned date columns

print("Employee Hire Dates:")
display(
    employees_df[["EmployeeID", "HireDate"]].head(10)
)

print("\nPerformance Review Dates:")
display(
    performance_df[
        ["PerformanceID", "EmployeeID", "ReviewDate"]
    ].head(10)
)

Employee Hire Dates:

  EmployeeID   HireDate
0  001A-8F88 2021-09-05
1  005C-E0FB 2017-08-26
2  00A3-2445 2012-03-08
3  00B0-F199 2020-03-16
4  00D4-DD53 2012-01-28
5  00E4-3D60 2022-06-23
6  0145-DBFC 2014-02-10
7  0172-B5D2 2020-09-11
8  017D-0B97 2020-03-30
9  018B-DF1E 2022-10-17

Performance Review Dates:

  PerformanceID EmployeeID ReviewDate
0          PR01  79F7-78EC 2013-01-02
1          PR02  B61E-0F26 2013-01-03
2          PR03  F5E3-48BB 2013-01-03
3          PR04  0678-748A 2013-01-04
4          PR05  541F-3E19 2013-01-04
5          PR06  F93E-BDEF 2013-01-04
6          PR07  9E7A-1F70 2013-01-08
7          PR08  05ED-92F1 2013-01-10
8          PR09  F72D-261D 2013-01-10
9          PR10  774E-685D 2013-01-11

In [17]:
# Validate Age

print("Age minimum:", employees_df["Age"].min())
print("Age maximum:", employees_df["Age"].max())

print("\nInvalid Age records:")
display(
    employees_df[
        (employees_df["Age"] < 18) |
        (employees_df["Age"] > 70)
    ][["EmployeeID", "Age"]]
)

Age minimum: 18
Age maximum: 51

Invalid Age records:

Empty DataFrame
Columns: [EmployeeID, Age]
Index: []

In [18]:
# Validate YearsAtCompany

print("YearsAtCompany minimum:",
      employees_df["YearsAtCompany"].min())

print("YearsAtCompany maximum:",
      employees_df["YearsAtCompany"].max())

print("\nInvalid YearsAtCompany records:")

display(
    employees_df[
        (employees_df["YearsAtCompany"] < 0) |
        (employees_df["YearsAtCompany"] > employees_df["Age"])
    ][["EmployeeID", "Age", "YearsAtCompany"]]
)

YearsAtCompany minimum: 0
YearsAtCompany maximum: 10

Invalid YearsAtCompany records:

Empty DataFrame
Columns: [EmployeeID, Age, YearsAtCompany]
Index: []

In [19]:
# Validate satisfaction ratings

satisfaction_columns = [
    column for column in employees_df.columns
    if "Satisfaction" in column
]

print("Satisfaction columns found:")
print(satisfaction_columns)

print("\nSATISFACTION RATING VALIDATION")

for column in satisfaction_columns:
    print(
        column,
        "| Min:", employees_df[column].min(),
        "| Max:", employees_df[column].max()
    )

    # Check values outside the expected 1–5 range
    invalid_values = employees_df[
        (employees_df[column] < 1) |
        (employees_df[column] > 5)
    ]

    print("Invalid records:", len(invalid_values))
    print()

Satisfaction columns found:
[]

SATISFACTION RATING VALIDATION

In [20]:
# Validate performance ratings

rating_columns = [
    "SelfRating",
    "ManagerRating"
]

print("PERFORMANCE RATING VALIDATION")

for column in rating_columns:
    if column in performance_df.columns:
        print(
            column,
            "| Min:", performance_df[column].min(),
            "| Max:", performance_df[column].max()
        )

        # Check values outside expected 1–5 range
        invalid_values = performance_df[
            (performance_df[column] < 1) |
            (performance_df[column] > 5)
        ]

        print("Invalid records:", len(invalid_values))
    else:
        print("Column not found:", column)

PERFORMANCE RATING VALIDATION
SelfRating | Min: 3 | Max: 5
Invalid records: 0
ManagerRating | Min: 2 | Max: 5
Invalid records: 0

In [21]:
# Check categorical values

categorical_columns = [
    "Gender",
    "BusinessTravel",
    "Department",
    "State",
    "Ethnicity",
    "JobRole",
    "MaritalStatus"
]

print("CATEGORICAL VALUE CHECK")

for column in categorical_columns:
    if column in employees_df.columns:
        print(f"\n{column}:")
        print(employees_df[column].value_counts(dropna=False))
    else:
        print(f"\nColumn not found: {column}")

CATEGORICAL VALUE CHECK

Gender:
Gender
Female               675
Male                 651
Non-Binary           124
Prefer Not To Say     20
Name: count, dtype: int64

BusinessTravel:
BusinessTravel
Some Travel           1043
Frequent Traveller     277
No Travel              150
Name: count, dtype: int64

Department:
Department
Technology         961
Sales              446
Human Resources     63
Name: count, dtype: int64

State:
State
CA    875
NY    419
IL    176
Name: count, dtype: int64

Ethnicity:
Ethnicity
White                               860
Black or African American           207
Mixed or multiple ethnic groups     198
Asian or Asian American             113
American Indian or Alaska Native     50
Native Hawaiian                      26
Other                                16
Name: count, dtype: int64

JobRole:
JobRole
Sales Executive              327
Software Engineer            294
Data Scientist               261
Machine Learning Engineer    146
Senior Software Engineer     132
Sales Representative          83
Engineering Manager           75
Analytics Manager             52
Manager                       37
HR Executive                  28
Recruiter                     24
HR Business Partner            7
HR Manager                     4
Name: count, dtype: int64

MaritalStatus:
MaritalStatus
Married     624
Single      549
Divorced    297
Name: count, dtype: int64

In [22]:
# Handling Missing Values
# Check missing values before cleaning

print("EMPLOYEES")
print(employees_df.isnull().sum()[employees_df.isnull().sum() > 0])

print("\nPERFORMANCE RATINGS")
print(performance_df.isnull().sum()[performance_df.isnull().sum() > 0])

# Fill missing numerical values with median
numeric_employee_columns = employees_df.select_dtypes(
    include="number"
).columns
for column in numeric_employee_columns:
    if employees_df[column].isnull().sum() > 0:
        employees_df[column] = employees_df[column].fillna(
            employees_df[column].median()
        )
numeric_performance_columns = performance_df.select_dtypes(
    include="number"
).columns

for column in numeric_performance_columns:
    if performance_df[column].isnull().sum() > 0:
        performance_df[column] = performance_df[column].fillna(
            performance_df[column].median()
        )
print("\nMissing numerical values handled.")

# Fill missing categorical values
categorical_employee_columns = employees_df.select_dtypes(
    include="object"
).columns
for column in categorical_employee_columns:
    employees_df[column] = employees_df[column].fillna("Unknown")
categorical_performance_columns = performance_df.select_dtypes(
    include="object"
).columns
for column in categorical_performance_columns:
    performance_df[column] = performance_df[column].fillna("Unknown")
print("\nMissing categorical values handled.")

EMPLOYEES
Series([], dtype: int64)

PERFORMANCE RATINGS
Series([], dtype: int64)

Missing numerical values handled.

Missing categorical values handled.

C:\Users\Shiva\AppData\Local\Temp\ipykernel_12856\1665111690.py:31: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_employee_columns = employees_df.select_dtypes(
C:\Users\Shiva\AppData\Local\Temp\ipykernel_12856\1665111690.py:36: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_performance_columns = performance_df.select_dtypes(

In [23]:
# Remove duplicate records

employee_duplicates = employees_df.duplicated().sum()
performance_duplicates = performance_df.duplicated().sum()

print("Employee duplicate rows:", employee_duplicates)
print("Performance duplicate rows:", performance_duplicates)

if employee_duplicates > 0:
    employees_df = employees_df.drop_duplicates()

if performance_duplicates > 0:
    performance_df = performance_df.drop_duplicates()

print("\nDuplicates handled successfully.")
print("Employees rows:", len(employees_df))
print("Performance rows:", len(performance_df))

Employee duplicate rows: 0
Performance duplicate rows: 0

Duplicates handled successfully.
Employees rows: 1470
Performance rows: 6709

## Detailed Missing-Value Analysis

This section identifies missing values, measures their percentage,
and evaluates the extent of missing data before applying any treatment.

In [24]:
# Detailed missing-value report for employees

employees_missing_report = pd.DataFrame({
    "Missing_Count": employees_df.isnull().sum(),
    "Missing_Percentage": (
        employees_df.isnull().sum() / len(employees_df) * 100
    ).round(2),
    "Data_Type": employees_df.dtypes.astype(str)
})
employees_missing_report = (
    employees_missing_report
    .sort_values("Missing_Count", ascending=False)
)
display(employees_missing_report)

                         Missing_Count  Missing_Percentage      Data_Type
EmployeeID                           0                 0.0            str
FirstName                            0                 0.0            str
LastName                             0                 0.0            str
Gender                               0                 0.0            str
Age                                  0                 0.0          int64
BusinessTravel                       0                 0.0            str
Department                           0                 0.0            str
DistanceFromHome_KM                  0                 0.0          int64
State                                0                 0.0            str
Ethnicity                            0                 0.0            str
Education                            0                 0.0          int64
EducationField                       0                 0.0            str
JobRole                              0                 0.0            str
MaritalStatus                        0                 0.0            str
Salary                               0                 0.0        float64
StockOptionLevel                     0                 0.0          int64
OverTime                             0                 0.0            str
HireDate                             0                 0.0  datetime64[s]
Attrition                            0                 0.0            str
YearsAtCompany                       0                 0.0          int64
YearsInMostRecentRole                0                 0.0          int64
YearsSinceLastPromotion              0                 0.0          int64
YearsWithCurrManager                 0                 0.0          int64

In [25]:
# Detailed missing-value report for performance ratings

performance_missing_report = pd.DataFrame({
    "Missing_Count": performance_df.isnull().sum(),
    "Missing_Percentage": (
        performance_df.isnull().sum() / len(performance_df) * 100
    ).round(2),
    "Data_Type": performance_df.dtypes.astype(str)
})

performance_missing_report = (
    performance_missing_report
    .sort_values("Missing_Count", ascending=False)
)

display(performance_missing_report)

,Missing_Count,Missing_Percentage,Data_Type
PerformanceID,0,0.0,str
EmployeeID,0,0.0,str
ReviewDate,0,0.0,datetime64[s]
EnvironmentSatisfaction,0,0.0,int64
JobSatisfaction,0,0.0,int64
RelationshipSatisfaction,0,0.0,int64
TrainingOpportunitiesWithinYear,0,0.0,int64
TrainingOpportunitiesTaken,0,0.0,int64
WorkLifeBalance,0,0.0,int64
SelfRating,0,0.0,int64
ManagerRating,0,0.0,int64

In [26]:
# Display cloumns with missing values
# Employees: columns containing missing values

print("Employees:",employees_missing_report[
    employees_missing_report["Missing_Count"] > 0
])

# Performance: columns containing missing values

print("Performance:",performance_missing_report[
    performance_missing_report["Missing_Count"] > 0
])

Employees: Empty DataFrame
Columns: [Missing_Count, Missing_Percentage, Data_Type]
Index: []
Performance: Empty DataFrame
Columns: [Missing_Count, Missing_Percentage, Data_Type]
Index: []

In [27]:
# Overall missing-value percentage

employee_total_cells = employees_df.size
employee_missing_cells = employees_df.isnull().sum().sum()

performance_total_cells = performance_df.size
performance_missing_cells = performance_df.isnull().sum().sum()

employee_missing_percentage = (
    employee_missing_cells / employee_total_cells * 100
)

performance_missing_percentage = (
    performance_missing_cells / performance_total_cells * 100
)

print(
    f"Employees overall missing percentage: "
    f"{employee_missing_percentage:.2f}%"
)

print(
    f"Performance overall missing percentage: "
    f"{performance_missing_percentage:.2f}%"
)

Employees overall missing percentage: 0.00%
Performance overall missing percentage: 0.00%

## Duplicate Record Analysis

This section identifies exact duplicate rows and duplicate business keys
to ensure that employee and performance records are uniquely represented.

In [28]:
# Check exact duplicate rows

employee_exact_duplicates = employees_df.duplicated().sum()
performance_exact_duplicates = performance_df.duplicated().sum()

print("Employee exact duplicates:", employee_exact_duplicates)
print("Performance exact duplicates:", performance_exact_duplicates)

Employee exact duplicates: 0
Performance exact duplicates: 0

In [29]:
# Check duplicate EmployeeIDs

employee_id_duplicates = (
    employees_df["EmployeeID"]
    .duplicated()
    .sum()
)

print("Duplicate EmployeeIDs:", employee_id_duplicates)

Duplicate EmployeeIDs: 0

In [30]:
# Check duplicate PerformanceIDs

performance_id_duplicates = (
    performance_df["PerformanceID"]
    .duplicated()
    .sum()
)

print("Duplicate PerformanceIDs:", performance_id_duplicates)

Duplicate PerformanceIDs: 0

In [31]:
# Display duplicate employee records

duplicate_employees = employees_df[
    employees_df["EmployeeID"].duplicated(keep=False)
].sort_values("EmployeeID")

display(duplicate_employees)

Empty DataFrame
Columns: [EmployeeID, FirstName, LastName, Gender, Age, BusinessTravel, Department, DistanceFromHome_KM, State, Ethnicity, Education, EducationField, JobRole, MaritalStatus, Salary, StockOptionLevel, OverTime, HireDate, Attrition, YearsAtCompany, YearsInMostRecentRole, YearsSinceLastPromotion, YearsWithCurrManager]
Index: []

[0 rows x 23 columns]

In [32]:
# Display duplicate performance records

duplicate_performance = performance_df[
    performance_df["PerformanceID"].duplicated(keep=False)
].sort_values("PerformanceID")

display(duplicate_performance)

Empty DataFrame
Columns: [PerformanceID, EmployeeID, ReviewDate, EnvironmentSatisfaction, JobSatisfaction, RelationshipSatisfaction, TrainingOpportunitiesWithinYear, TrainingOpportunitiesTaken, WorkLifeBalance, SelfRating, ManagerRating]
Index: []

## EmployeeID & Referential Integrity Validation

This section verifies that every EmployeeID in the performance dataset
exists in the employee master dataset.

In [33]:
# Find EmployeeIDs in performance data that do not exist in employees

employee_ids = set(employees_df["EmployeeID"].dropna())
performance_employee_ids = set(
    performance_df["EmployeeID"].dropna()
)

unmatched_employee_ids = (
    performance_employee_ids - employee_ids
)

print(
    "Unmatched EmployeeIDs:",
    len(unmatched_employee_ids)
)

Unmatched EmployeeIDs: 0

In [34]:
# Display performance records with unmatched EmployeeIDs

unmatched_records = performance_df[
    ~performance_df["EmployeeID"].isin(employee_ids)
]

display(unmatched_records)

Empty DataFrame
Columns: [PerformanceID, EmployeeID, ReviewDate, EnvironmentSatisfaction, JobSatisfaction, RelationshipSatisfaction, TrainingOpportunitiesWithinYear, TrainingOpportunitiesTaken, WorkLifeBalance, SelfRating, ManagerRating]
Index: []

In [35]:
# Check missing EmployeeIDs in both datasets

print(
    "Missing EmployeeIDs in employees:",
    employees_df["EmployeeID"].isna().sum()
)

print(
    "Missing EmployeeIDs in performance:",
    performance_df["EmployeeID"].isna().sum()
)

Missing EmployeeIDs in employees: 0
Missing EmployeeIDs in performance: 0

In [36]:
# Calculate referential integrity coverage
matched_records = performance_df[
    performance_df["EmployeeID"].isin(employee_ids)
]
coverage_percentage = (
    len(matched_records) /
    len(performance_df) *
    100
)
print(
    f"Employee relationship coverage: "
    f"{coverage_percentage:.2f}%"
)

Employee relationship coverage: 100.00%

## Numerical Data Quality & Business Rule Validation

This section validates numerical fields and checks whether employee
data follows reasonable business and logical rules.

In [37]:
# Check age range
print("Minimum age:", employees_df["Age"].min())
print("Maximum age:", employees_df["Age"].max())

invalid_age = employees_df[
    (employees_df["Age"] < 18) |
    (employees_df["Age"] > 70)
]

print("\nInvalid age records:", len(invalid_age))

display(
    invalid_age[
        ["EmployeeID", "FirstName", "LastName", "Age"]
    ]
)

Minimum age: 18
Maximum age: 51

Invalid age records: 0

Empty DataFrame
Columns: [EmployeeID, FirstName, LastName, Age]
Index: []

In [38]:
# Check salary range
print("Minimum salary:", employees_df["Salary"].min())
print("Maximum salary:", employees_df["Salary"].max())

invalid_salary = employees_df[
    employees_df["Salary"] <= 0
]

print("\nInvalid salary records:", len(invalid_salary))

display(
    invalid_salary[
        ["EmployeeID", "FirstName", "LastName", "Salary"]
    ]
)

Minimum salary: 20387.0
Maximum salary: 547204.0

Invalid salary records: 0

Empty DataFrame
Columns: [EmployeeID, FirstName, LastName, Salary]
Index: []

In [39]:
# Check DistanceFromHome_KM

print("Minimum distance from home:", employees_df["DistanceFromHome_KM"].min())
print("Maximum distance from home:", employees_df["DistanceFromHome_KM"].max())

invalid_distance = employees_df[
    employees_df["DistanceFromHome_KM"] <0
]
print("\nInvalid distance records:", len(invalid_distance))

display(
    invalid_distance[
        ["EmployeeID", "DistanceFromHome_KM"]
    ]
)

Minimum distance from home: 1
Maximum distance from home: 45

Invalid distance records: 0

Empty DataFrame
Columns: [EmployeeID, DistanceFromHome_KM]
Index: []

In [40]:
# Check YearsAtCompany

print("Minimum YearsAtCompany:",employees_df["YearsAtCompany"].min())
print("Maximum YearsAtCompany:",employees_df["YearsAtCompany"].max())

invalid_company_years = employees_df[
    (employees_df["YearsAtCompany"] < 0) |
    (employees_df["YearsAtCompany"] > employees_df["Age"])
]
print("\nInvalid YearsAtCompany records:",len(invalid_company_years))

display(
    invalid_company_years[
        ["EmployeeID","Age","YearsAtCompany"]
    ]
)

Minimum YearsAtCompany: 0
Maximum YearsAtCompany: 10

Invalid YearsAtCompany records: 0

Empty DataFrame
Columns: [EmployeeID, Age, YearsAtCompany]
Index: []

In [41]:
# Validate YearsInMostRecentRole

invalid_role_years = employees_df[
    (employees_df["YearsInMostRecentRole"] < 0) |
    (
        employees_df["YearsInMostRecentRole"]
        > employees_df["YearsAtCompany"]
    )
]
print("Invalid YearsInMostRecentRole records:",len(invalid_role_years))
display(
    invalid_role_years[
        ["EmployeeID", "YearsAtCompany","YearsInMostRecentRole"]
    ]
)

Invalid YearsInMostRecentRole records: 0

Empty DataFrame
Columns: [EmployeeID, YearsAtCompany, YearsInMostRecentRole]
Index: []

In [42]:
# Validate YearsWithCurrManager

invalid_manager_years = employees_df[
    (employees_df["YearsWithCurrManager"] < 0) |
    (
        employees_df["YearsWithCurrManager"]
        > employees_df["YearsAtCompany"]
    )
]
print("Invalid YearsWithCurrManager records:",len(invalid_manager_years))
display(
    invalid_manager_years[
        ["EmployeeID","YearsAtCompany","YearsWithCurrManager"]
    ]
)

Invalid YearsWithCurrManager records: 0

Empty DataFrame
Columns: [EmployeeID, YearsAtCompany, YearsWithCurrManager]
Index: []

In [43]:
# Validate YearsSinceLastPromotion

invalid_promotion_years = employees_df[
    (employees_df["YearsSinceLastPromotion"] < 0) |
    (
        employees_df["YearsSinceLastPromotion"]
        > employees_df["YearsAtCompany"]
    )
]
print("Invalid YearsSinceLastPromotion records:",len(invalid_promotion_years))
display(
    invalid_promotion_years[
        ["EmployeeID","YearsAtCompany","YearsSinceLastPromotion"]
    ]
)

Invalid YearsSinceLastPromotion records: 0

Empty DataFrame
Columns: [EmployeeID, YearsAtCompany, YearsSinceLastPromotion]
Index: []

In [44]:
# Business rule validation summary

validation_summary = {
    "Invalid Age": len(invalid_age),
    "Invalid Salary": len(invalid_salary),
    "Invalid Distance": len(invalid_distance),
    "Invalid YearsAtCompany": len(invalid_company_years),
    "Invalid YearsInMostRecentRole": len(invalid_role_years),
    "Invalid YearsSinceLastPromotion": len(invalid_promotion_years),
    "Invalid YearsWithCurrManager": len(invalid_manager_years)
}
validation_summary_df = pd.DataFrame(
    list(validation_summary.items()),
    columns=["Validation_Check", "Invalid_Record_Count"]
)

display(validation_summary_df)

                  Validation_Check  Invalid_Record_Count
0                      Invalid Age                     0
1                   Invalid Salary                     0
2                 Invalid Distance                     0
3           Invalid YearsAtCompany                     0
4    Invalid YearsInMostRecentRole                     0
5  Invalid YearsSinceLastPromotion                     0
6     Invalid YearsWithCurrManager                     0

## Rating & Categorical Data Validation

This section validates rating scales and categorical variables
to identify invalid, inconsistent, or unexpected values.

In [45]:
# Find satisfaction columns
satisfaction_columns = [
    column
    for column in employees_df.columns
    if "Satisfaction" in column
]

print("Satisfaction columns:")
print(satisfaction_columns)

Satisfaction columns:
[]

In [46]:
# Validate satisfaction rating ranges

for column in satisfaction_columns:
    print(f"\n{column}")
    print("Unique values:", sorted(employees_df[column].dropna().unique()))
    
    invalid_count = employees_df[
        (employees_df[column] < 1) |
        (employees_df[column] > 5)
    ].shape[0]
    
    print("Invalid records:", invalid_count)

In [47]:
# Validate performance rating ranges

rating_columns = [
    "SelfRating",
    "ManagerRating"
]

for column in rating_columns:
    print(f"\n{column}")
    print("Unique values:", sorted(performance_df[column].dropna().unique()))
    
    invalid_count = performance_df[
        (performance_df[column] < 1) |
        (performance_df[column] > 5)
    ].shape[0]
    
    print("Invalid records:", invalid_count)

SelfRating
Unique values: [np.int64(3), np.int64(4), np.int64(5)]
Invalid records: 0

ManagerRating
Unique values: [np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Invalid records: 0

In [48]:
# Validate Attrition values

print("Attrition values:")
print(employees_df["Attrition"].value_counts(dropna=False))

Attrition values:
Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [49]:
valid_attrition = {"Yes", "No"}

invalid_attrition = employees_df[
    ~employees_df["Attrition"].isin(valid_attrition)
]

print("Invalid Attrition records:",
      len(invalid_attrition))

display(
    invalid_attrition[
        ["EmployeeID", "Attrition"]
    ]
)

Invalid Attrition records: 0

Empty DataFrame
Columns: [EmployeeID, Attrition]
Index: []

In [50]:
# Validate Gender values

print("Gender values:")
print(employees_df["Gender"].value_counts(dropna=False))

Gender values:
Gender
Female               675
Male                 651
Non-Binary           124
Prefer Not To Say     20
Name: count, dtype: int64

In [52]:
# Validate BusinessTravel values

print("BusinessTravel values:")
print(employees_df["BusinessTravel"].value_counts(dropna=False))

BusinessTravel values:
BusinessTravel
Some Travel           1043
Frequent Traveller     277
No Travel              150
Name: count, dtype: int64

In [53]:
# Validate Department values

print("Department values:")
print(employees_df["Department"].value_counts(dropna=False))

Department values:
Department
Technology         961
Sales              446
Human Resources     63
Name: count, dtype: int64

In [54]:
# Validate JobRole values

print("JobRole values:")
print(employees_df["JobRole"].value_counts(dropna=False))

JobRole values:
JobRole
Sales Executive              327
Software Engineer            294
Data Scientist               261
Machine Learning Engineer    146
Senior Software Engineer     132
Sales Representative          83
Engineering Manager           75
Analytics Manager             52
Manager                       37
HR Executive                  28
Recruiter                     24
HR Business Partner            7
HR Manager                     4
Name: count, dtype: int64

In [55]:
# Validate MaritalStatus values

print("MaritalStatus values:")
print(employees_df["MaritalStatus"].value_counts(dropna=False))

MaritalStatus values:
MaritalStatus
Married     624
Single      549
Divorced    297
Name: count, dtype: int64

In [56]:
# Check for leading or trailing spaces in text columns

text_columns = employees_df.select_dtypes(include="object").columns
for column in text_columns:
    if employees_df[column].astype(str).str.strip().ne(
        employees_df[column].astype(str)
    ).any():
        print("Spaces found in:", column)

C:\Users\Shiva\AppData\Local\Temp\ipykernel_12856\3855038204.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = employees_df.select_dtypes(include="object").columns

Spaces found in: BusinessTravel
Spaces found in: Ethnicity
Spaces found in: EducationField

In [57]:
# Clean leading and trailing spaces from text columns

text_columns = employees_df.select_dtypes(
    include=["object", "string"]
).columns

for column in text_columns:
    employees_df[column] = employees_df[column].str.strip()

print("Text columns cleaned successfully!")

Text columns cleaned successfully!

In [58]:
# Verify text columns after cleaning

for column in text_columns:
    spaces_found = (
        employees_df[column]
        .astype("string")
        .str.strip()
        .ne(employees_df[column].astype("string"))
        .sum()
    )

    if spaces_found > 0:
        print(f"{column}: {spaces_found} spaces still found")

print("Text cleaning verification completed.")

Text cleaning verification completed.

In [59]:
# Check for leading or trailing spaces in text columns

text_columns = employees_df.select_dtypes(include="object").columns
for column in text_columns:
    if employees_df[column].astype(str).str.strip().ne(
        employees_df[column].astype(str)
    ).any():
        print("Spaces found in:", column)

C:\Users\Shiva\AppData\Local\Temp\ipykernel_12856\3855038204.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = employees_df.select_dtypes(include="object").columns

In [60]:
# Remove leading and trailing spaces

for column in text_columns:
    employees_df[column] = (
        employees_df[column]
        .astype("string")
        .str.strip()
    )

for column in performance_df.select_dtypes(
    include="object"
).columns:
    performance_df[column] = (
        performance_df[column]
        .astype("string")
        .str.strip()
    )

print("Text formatting standardized.")

Text formatting standardized.

C:\Users\Shiva\AppData\Local\Temp\ipykernel_12856\2594314336.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in performance_df.select_dtypes(

## Business Rule Validation

Validate HR-specific logical relationships between numerical fields
to identify inconsistent employee records.

In [64]:
# Check YearsAtCompany vs YearsInMostRecentRole
invalid_role_years = employees_df[
    employees_df["YearsInMostRecentRole"] > employees_df["YearsAtCompany"]
]
print("Invalid YearsInMostRecentRole records:",len(invalid_role_years))

Invalid YearsInMostRecentRole records: 0

In [65]:
# Check YearsAtCompany vs YearsSinceLastPromotion

invalid_promotion_years = employees_df[
    employees_df["YearsSinceLastPromotion"] > employees_df["YearsAtCompany"]
]
print("Invalid YearsSinceLastPromotion records:",len(invalid_promotion_years))

Invalid YearsSinceLastPromotion records: 0

In [66]:
# Check YearsAtCompany vs YearsWithCurrManager

invalid_manager_years = employees_df[
    employees_df["YearsWithCurrManager"] > employees_df["YearsAtCompany"]
]
print("Invalid YearsWithCurrManager records:",len(invalid_manager_years))

Invalid YearsWithCurrManager records: 0

In [68]:
# Check DistanceFromHome

invalid_distance = employees_df[
    employees_df["DistanceFromHome_KM"] < 0
]
print("Invalid DistanceFromHome records:",len(invalid_distance))

Invalid DistanceFromHome records: 0

In [73]:
# Check employee age range
invalid_age = employees_df[
    (employees_df["Age"] < 18) |
    (employees_df["Age"] > 100)
]
print("Invalid Age records:", len(invalid_age))

Invalid Age records: 0

In [74]:
employees_clean = employees_df.copy()
performance_clean = performance_df.copy()

print("Clean datasets created successfully!")
print("Employees:", employees_clean.shape)
print("Performance:", performance_clean.shape)

Clean datasets created successfully!
Employees: (1470, 23)
Performance: (6709, 11)

In [75]:
# SAVE CLEANED DATASETS
from pathlib import Path

# Create cleaned_data folder
cleaned_data_path = Path("cleaned_data")
cleaned_data_path.mkdir(exist_ok=True)

# Save employees dataset
employees_clean.to_csv(
    cleaned_data_path / "employees_clean.csv",
    index=False
)

# Save performance dataset
performance_clean.to_csv(
    cleaned_data_path / "performance_clean.csv",
    index=False
)

print("Clean CSV files saved successfully!")
print("Employees:", cleaned_data_path / "employees_clean.csv")
print("Performance:", cleaned_data_path / "performance_clean.csv")

Clean CSV files saved successfully!
Employees: cleaned_data\employees_clean.csv
Performance: cleaned_data\performance_clean.csv

In [76]:
# Verify clean csv files 
employees_check = pd.read_csv(
    cleaned_data_path / "employees_clean.csv"
)

performance_check = pd.read_csv(
    cleaned_data_path / "performance_clean.csv"
)

print("FINAL VERIFICATION")

print("\nEmployees Clean CSV")
print("Rows:", employees_check.shape[0])
print("Columns:", employees_check.shape[1])
print("Missing values:", employees_check.isnull().sum().sum())
print("Duplicate rows:", employees_check.duplicated().sum())

print("\nPerformance Clean CSV")
print("Rows:", performance_check.shape[0])
print("Columns:", performance_check.shape[1])
print("Missing values:", performance_check.isnull().sum().sum())
print("Duplicate rows:", performance_check.duplicated().sum())

FINAL VERIFICATION

Employees Clean CSV
Rows: 1470
Columns: 23
Missing values: 0
Duplicate rows: 0

Performance Clean CSV
Rows: 6709
Columns: 11
Missing values: 0
Duplicate rows: 0